---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    name: Review
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      check_commits: false
      check_policy: true
      policy_source: https://github.com/appvia/terranetes-workflows
      policy_version: ''

  release:
    needs: verify
    name: Release
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    with:
      enable_release: true
