---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
